### ISSUE TITLE
Access denied instead of 404

### ISSUE THREAD

**Issue by sumanthratna** [ray-project/travis-tracker-v2#3]
when I navigate to a page like https://flakey-tests.ray.io/hello, I see:
> This XML file does not appear to have any style information associated with it. The document tree is shown below.
> 
> ---
> 
> ```xml
> <Error>
> <Code>AccessDenied</Code>
> <Message>Access Denied</Message>
> <RequestId>4D38D8DDD397DF71</RequestId>
> <HostId>hLdzL3qBQ2ln8O6pusXgovRCU7Ppa3pu1SLR4ZTuBrulRSqe8FLib6bqKgmYChqdSMiGbqPLUfo=</HostId>
> </Error>
> ```

I would expect a simple 404

**Comment by sumanthratna** [comment]
reopening; server-side settings need to be changed https://github.com/ray-project/travis-tracker-v2/pull/4#issuecomment-703203388

**Comment by simon-mo** [comment]
Should be fixed now.
