### ISSUE TITLE
Release tests filter doesn't work

### ISSUE THREAD

**Issue by cadedaniel** [ray-project/travis-tracker-v2#34]
Clicking "Only" for release tests yields zero test results

<img width="318" alt="Screen Shot 2023-01-23 at 5 59 57 PM" src="https://user-images.githubusercontent.com/950914/214197581-c95d106c-1885-465e-9122-d3a8ae1a3c7d.png">

**Comment by cadedaniel** [comment]
Hi @simon-mo , I see this commit https://github.com/ray-project/travis-tracker-v2/commit/b92eb47ba77b7f0bc9807d89080d2bc00c937c98 disabled release test reporting. Do you remember why? I'd love to re-enable them, welcome any pointers.

**Comment by simon-mo** [comment]
I believe it was broken due to the massive artifact size increase from @Yard1's metrics addition to result json. Feel free to try to re-enable it and see what happen! My guess is the current code doesn't deal with large result file using up memory and/or disk

**Comment by Yard1** [comment]
The metrics are no longer reported to database btw, so this shouldn't be an issue anymore.

**Comment by cadedaniel** [comment]
Ok, created https://github.com/ray-project/travis-tracker-v2/pull/36
